version: '3'
services:
  web:
    build: .
    depends_on:
      - db
      - redis
      - sidekiq
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: bundle exec rails s -b 0.0.0.0
  sidekiq:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    command: bundle exec sidekiq
  db:
    image: postgres
  redis:
    image: redis
